name: NuGet Publish

on: push

jobs:
  build:
    if: github.event.base_ref == 'refs/heads/release'
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Set version
      run: |
        echo "VERSION=$(date +%Y.%-m.%-d.%-H%M%S)" >> $GITHUB_ENV
        echo "Version: $VERSION"
    
    - name: Tag commit
      run: |
        git tag v$VERSION ${{ github.sha }}
        git push origin v$VERSION

    - name: Setup .NET
      uses: actions/setup-dotnet@v1.7.2
      with:
        dotnet-version: 5.0.x

    - name: Restore dependencies
      run: dotnet restore ./src/BlazorEasyAuth/BlazorEasyAuth.csproj

    - name: dotnet pack
      run: dotnet pack ./src/BlazorEasyAuth/BlazorEasyAuth.csproj -o ./pack -p:PackageVersion=${{ env.VERSION }} -c Release --no-restore --include-symbols -p:SymbolPackageFormat=snupkg

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: Packed
        path: ./pack
        retention-days: 1

    - name: Push NuGet package
      run: dotnet nuget push ./pack/*.nupkg -k ${{ secrets.NUGETAPIKEY }} -s https://api.nuget.org/v3/index.json
