name: .NET

on:
  push:
    tags:
      - '1.*.*'

jobs:
  build:
    if: github.event.base_ref == 'refs/heads/release'
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: Get version number
      run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

    - name: Setup .NET
      uses: actions/setup-dotnet@v1.7.2
      with:
        dotnet-version: 5.0.x

    - name: Restore dependencies
      run: dotnet restore ./src/BlazorEasyAuth/BlazorEasyAuth.csproj

    - name: dotnet pack
      run: dotnet pack ./src/BlazorEasyAuth/BlazorEasyAuth.csproj -o ./pack -p:PackageVersion=${{ env.RELEASE_VERSION }} -c Release --no-restore --include-symbols

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: Packed
        path: ./pack
        retention-days: 1

    - name: Push NuGet package
      run: dotnet nuget push ./pack/*.nupkg -k ${{ secrets.NUGETAPIKEY }} -s https://api.nuget.org/v3/index.json
